project_id = "dfobnipqgkjivupcufgv"

[functions.fetch-subawards-data]
verify_jwt = false

[functions.fetch-usaspending-data]
verify_jwt = false

[functions.fetch-grants-data]
verify_jwt = false

[functions.fetch-nasbo-data]
verify_jwt = false

[functions.admin-clear-data]
verify_jwt = false

[functions.push-to-clay]
verify_jwt = false

[functions.discovery-search]
verify_jwt = false
